Controllers/TheatreController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MovieApp.Entity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieApp.UI.Controllers
{
    public class TheatreController : Controller
    {
        IConfiguration _iConfiguration;

        public TheatreController(IConfiguration configuration)
        {
            _iConfiguration = configuration;
        }
        public async Task<IActionResult> ShowTheatreDetails()
        {
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _iConfiguration["WebApiUrl"] + "Theatre/SelectTheatres";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var theatreModel = JsonConvert.DeserializeObject<List<TheatreModel>>(result);
                        return View(theatreModel);
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Cant fetch any data";
                    }
                }
            }
            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(TheatreModel theatreModel)
        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(theatreModel), Encoding.UTF8, "application/json");
                string endpoint = _iConfiguration["WebApiUrl"] + "Theatre/RegisterTheatre";
                using (var response = await client.PostAsync(endpoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = "Registration Successful";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Registration Unsuccessful";
                    }
                }
            }
            return View();
        }

        public async Task<IActionResult> UpdateTheatre(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _iConfiguration["WebApiUrl"] + "Theatre/GetTheatreById?id=" + id;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var theatreModel = JsonConvert.DeserializeObject<TheatreModel>(result);
                        return View(theatreModel);
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Cant fetch any data";
                    }
                }
            }
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> UpdateTheatre(TheatreModel theatreModel)
        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(theatreModel), Encoding.UTF8, "application/json");
                string endpoint = _iConfiguration["WebApiUrl"] + "Theatre/UpdateTheatre";
                using (var response = await client.PutAsync(endpoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = "Updation Successful";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Registration Unsuccessful";
                    }
                }
            }
            return View();
        }


        public async Task<IActionResult> DeleteTheatre(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _iConfiguration["WebApiUrl"] + "Theatre/GetTheatreById?id=" + id;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var theatreModel = JsonConvert.DeserializeObject<TheatreModel>(result);
                        return View(theatreModel);
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Cant fetch any data";
                    }
                }
            }
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> DeleteTheatre(TheatreModel theatreModel)
        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(theatreModel), Encoding.UTF8, "application/json");
                string endpoint = _iConfiguration["WebApiUrl"] + "Theatre/DeleteTheatre?id=" + theatreModel.TheatreId;
                using (var response = await client.PutAsync(endpoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = "Deletion Successful";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Deletion Unsuccessful";
                    }
                }
            }
            return View();
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using MovieApp.Entity;
using Newtonsoft.Json;
using System.Text;

namespace MovieApp.UI.Controllers
{
    public class UserController : Controller
    {
        IConfiguration _iConfiguration;

        public UserController(IConfiguration configuration)
        {
            _iConfiguration = configuration;
        }
        public async Task<IActionResult> ShowUserDetails()
        {
            using(HttpClient client= new HttpClient())
            {
                string endPoint = _iConfiguration["WebApiUrl"] + "User/SelectUsers";
                using(var response= await client.GetAsync(endPoint))
                {
                    if(response.StatusCode== System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var userModel = JsonConvert.DeserializeObject<List<UserModel>>(result);
                        return View(userModel);
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Cant fetch any data";
                    }
                }
            }
            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserModel userModel)
        {
            using(HttpClient client= new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(userModel), Encoding.UTF8, "application/json");
                string endpoint = _iConfiguration["WebApiUrl"] + "User/Register";
                using(var response= await client.PostAsync(endpoint,content))
                {
                    if(response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = "Registration Successful";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Registration Unsuccessful";
                    }
                }
            }
            return View();
        }

        public async Task<IActionResult> UpdateUser(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _iConfiguration["WebApiUrl"] + "User/GetUserById?id="+id;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var userModel = JsonConvert.DeserializeObject<UserModel>(result);
                        return View(userModel);
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Cant fetch any data";
                    }
                }
            }
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> UpdateUser(UserModel userModel)
        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(userModel), Encoding.UTF8, "application/json");
                string endpoint = _iConfiguration["WebApiUrl"] + "User/Update";
                using (var response = await client.PutAsync(endpoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = "Updation Successful";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Registration Unsuccessful";
                    }
                }
            }
            return View();
        }


        public async Task<IActionResult> DeleteUser(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _iConfiguration["WebApiUrl"] + "User/GetUserById?id=" + id;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var userModel = JsonConvert.DeserializeObject<UserModel>(result);
                        return View(userModel);
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Cant fetch any data";
                    }
                }
            }
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> DeleteUser(UserModel userModel)
        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(userModel), Encoding.UTF8, "application/json");
                string endpoint = _iConfiguration["WebApiUrl"] + "User/Delete?id="+userModel.UserId;
                using (var response = await client.PutAsync(endpoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = "Deletion Successful";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Registration Unsuccessful";
                    }
                }
            }
            return View();
        }
    }
}

Views/Theatre/DeleteTheatre.cshtml
@model MovieApp.Entity.TheatreModel
@{
    ViewData["Title"] = "DeleteTheatre";
}

<h1>DeleteTheatre</h1>

<form method="post">
    <div class="form-group">
        <label for="fName">TheatreId:</label>
        <input type="text" class="form-control" id="fname" asp-for="TheatreId" disabled="disabled">
    </div>
    <div class="form-group">
        <label for="fName">TheatreName:</label>
        <input type="text" class="form-control" id="fname" asp-for="TheatreName" disabled="disabled">
    </div>
    <div class="form-group">
        <label for="lName">Capacity:</label>
        <input type="text" class="form-control" id="lname" asp-for="Capacity" disabled="disabled">
    </div>
    <div class="form-group">
        <label for="contact">City:</label>
        <input type="text" class="form-control" id="contact" asp-for="City" disabled="disabled">
    </div>
    <div class="form-group">
        <label for="email">Description:</label>
        <input type="text" class="form-control" id="email" asp-for="Description" disabled="disabled">
    </div>
    
    <button type="submit" class="btn btn-primary">Delete</button>
    <button type="reset" class="btn btn-secondary">Reset</button>
</form>

@if (ViewBag.status == "Success")
{
    <div class="alert alert-success">@ViewBag.message</div>
}
else
{
    <div class="alert alert-danger">@ViewBag.message</div>
}

Views/Theatre/Register.cshtml
@model MovieApp.Entity.TheatreModel
@{
    ViewData["Title"] = "Register";
}
<a asp-action="ShowTheatreDetails" asp-controller="Theatre">Movie Details</a>
<hr />
<h1>Register</h1>

<form method="post">
    <div class="form-group">
        <label for="name">TheatreName:</label>
        <input type="text" class="form-control" id="name" asp-for="TheatreName">
    </div>
    <div class="form-group">
        <label for="lName">Capacity:</label>
        <input type="text" class="form-control" id="rating" asp-for="Capacity">
    </div>
    <div class="form-group">
        <label for="contact">City:</label>
        <input type="text" class="form-control" id="Genre" asp-for="City">
    </div>
    <div class="form-group">
        <label for="contact">Description:</label>
        <input type="text" class="form-control" id="Genre" asp-for="Description">
    </div>
    <button type="submit" class="btn btn-primary">Register</button>
    <button type="reset" class="btn btn-secondary">Reset</button>
</form>

@if (ViewBag.status == "Success")
{
    <div class="alert alert-success">@ViewBag.message</div>
}
else
{
    <div class="alert alert-danger">@ViewBag.message</div>
}

Views/Theatre/ShowTheatreDetails.cshtml
@model IEnumerable<MovieApp.Entity.TheatreModel>
@{
    ViewData["Title"] = "ShowTheatreDetails";
}

<h1>ShowTheatreDetails</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>TheatreId</th>
            <th>TheatreName</th>
            <th>Capacity</th>
            <th>City</th>
            <th>Description</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var items in Model)
        {
            <tr>
                <td>@items.TheatreId</td>
                <td>@items.TheatreName</td>
                <td>@items.Capacity</td>
                <td>@items.City</td>
                <td>@items.Description</td>
                <td><a asp-action="UpdateUser" asp-controller="User" asp-route-UserId="@items.TheatreId">Edit</a></td>
                <td><a asp-action="DeleteUser" asp-controller="User" asp-route-UserId="@items.TheatreId">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

Views/Theatre/UpdateTheatre.cshtml
@model MovieApp.Entity.TheatreModel
@{
    ViewData["Title"] = "UpdateTheatre";
}

<h1>UpdateTheatre</h1>

<form method="post">
    <div class="form-group">
        <label for="fName">TheatreNamee:</label>
        <input type="text" class="form-control" id="fname" asp-for="TheatreName">
    </div>
    <div class="form-group">
        <label for="lName">Capacity:</label>
        <input type="text" class="form-control" id="lname" asp-for="Capacity">
    </div>
    <div class="form-group">
        <label for="contact">City:</label>
        <input type="text" class="form-control" id="contact" asp-for="City">
    </div>
    <div class="form-group">
        <label for="email">Description:</label>
        <input type="text" class="form-control" id="email" asp-for="Description">
    </div>
   
    <button type="submit" class="btn btn-primary">Update</button>
    <button type="reset" class="btn btn-secondary">Reset</button>
</form>

@if (ViewBag.status == "Success")
{
    <div class="alert alert-success">@ViewBag.message</div>
}
else
{
    <div class="alert alert-danger">@ViewBag.message</div>
}