Controllers/MovieShowtimeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using MovieApp.Entity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieApp.UI.Controllers
{
    public class MovieShowtimeController : Controller
    {
        IConfiguration _configuration;
        public MovieShowtimeController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public async Task<IActionResult> ShowMovieTime()
        {
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiURL"] + "MovieShowtime/GetAllMovieShowtimes";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var movieShowTimes = JsonConvert.DeserializeObject<List<MovieShowtimeModel>>(result);
                        return View(movieShowTimes);
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "No Data Found!";
                    }
                }
            }
            return View();
        }

        public async Task<IActionResult> InsertMovieShowTimes()
        {

            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiURL"] + "Movie/GetMovies";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var movieModel = JsonConvert.DeserializeObject<List<MovieModel>>(result);
                        List<SelectListItem> selectListItemsMovies = new List<SelectListItem>();
                        foreach (var item in movieModel)
                        {
                            SelectListItem selectListItem = new SelectListItem();
                            selectListItem.Text = item.Name;
                            selectListItem.Value = item.Id.ToString();
                            selectListItemsMovies.Add(selectListItem);
                            ViewBag.movieData = selectListItemsMovies;
                        }
                    }
                }
            }
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiURL"] + "Theatre/SelectTheatres";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var theatreModel = JsonConvert.DeserializeObject<List<TheatreModel>>(result);
                        List<SelectListItem> selectListItemsTheatre = new List<SelectListItem>();
                        foreach (var item in theatreModel)
                        {
                            SelectListItem selectListItem = new SelectListItem();
                            selectListItem.Text = item.TheatreName;
                            selectListItem.Value = item.TheatreId.ToString();
                            selectListItemsTheatre.Add(selectListItem);
                            ViewBag.theatreData = selectListItemsTheatre;
                        }
                    }
                }
            }

            return View();
        }

        [HttpPost]

        // [ValidateAntiForgeryToken] [Bind("ShowId,MovieId,TheatreId,ShowTime,Date")]
        public async Task<IActionResult> RegisterMovieShowTimes(MovieShowtimeModel movieShowTimeModel)
        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(movieShowTimeModel), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiURL"] + "MovieShowtime/RegisterMovieShowtime";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = "Inserted!";
                        //return RedirectToAction("ShowMovieTime", "MovieShowtime");
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }

            return View();
        }

        public async Task<IActionResult> UpdateMovieshowTimes(int ShowId)
        {
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiURL"] + "MovieShowtime/GetMovieShowtimeById?id=" + ShowId;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var movieShowTimes = JsonConvert.DeserializeObject<MovieShowtimeModel>(result);
                        return View(movieShowTimes);
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "No Data Found!";
                    }
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateMovieshowTimes(MovieShowtimeModel movieShowTimeModel)
        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(movieShowTimeModel), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiURL"] + "MovieShowtime/UpdateMovieShowtimeById";
                using (var response = await client.PutAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = "MovieShowTime-Updated-Successfuly!!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong-Entries!!";
                    }
                }
            }
            return View();
        }
        public async Task<IActionResult> DeleteMovieshowTimes(int ShowId)
        {
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiURL"] + "MovieShowtime/GetMovieShowtimeById?id=" + ShowId;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var movieShowtimes = JsonConvert.DeserializeObject<MovieShowtimeModel>(result);
                        return View(movieShowtimes);
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "No Data Found!";
                    }
                }
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> DeleteMovieshowTimes(MovieShowtimeModel movieShowtimeModel)
        {
            using (HttpClient client = new HttpClient())
            {

                string endPoint = _configuration["WebApiURL"] + "MovieShowtime/DeleteMovieShowtimeById?id=" + movieShowtimeModel.ShowId;
                using (var response = await client.DeleteAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = "MovieShowTime-Deleted-Successfuly!!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong-Entries!!";
                    }
                }
            }
            return View();
        }
    }
}

Views/MovieShowtime/DeleteMovieshowTimes.cshtml
@model MovieApp.Entity.MovieShowtimeModel
@{
    ViewData["Title"] = "DeleteMovieshowTimes";
}

<a asp-action="ShowMovieTime" asp-controller="MovieShowtime">View MovieShowTime</a>
<hr />
<h1>DeleteMovieshowTimes</h1>

<div class="container">
    <form method="post">
        <div class="form-group">
            <label>ShowId</label>
            <input asp-for="ShowId" class="form-control" disabled="disabled"/>
        </div>
        <div class="form-group">
            <label>MovieId</label>
            <input asp-for="MovieId" class="form-control" disabled="disabled"/>
        </div>
        <div class="form-group">
            <label>TheatreId</label>
            <input asp-for="TheatreId" class="form-control" disabled="disabled"/>
        </div>

        <div class="form-group">
            <label>ShowTime</label>
            <input type="time" asp-for="ShowTime" class="form-control" disabled="disabled"/>
        </div>

        <div class="form-group">
            <label>Date</label>
            <input type="date" asp-for="Date" class="form-control" disabled="disabled"/>
        </div>

        <hr />
        <div class="form-group col-sm-3">
            <input type="submit" value="Delete" class="btn btn-lg btn-block btn-primary" />
        </div>
        <div>
            <input type="button" value="Reset" class="btn-secondary" />
        </div>

        <hr />
        @if (ViewBag.status == "Success")
        {
            <div class="alert alert-success">
                @ViewBag.message
            </div>
        }
        else if (ViewBag.status == "Error")
        {
            <div class="alert alert-danger">
                @ViewBag.message
            </div>
        }
    </form>
</div>

Views/MovieShowtime/InsertMovieShowTimes.cshtml
@model MovieApp.Entity.MovieShowtimeModel
@{
    ViewData["Title"] = "InsertMovieShowTimes";
}
<a asp-action="ShowMovieTime" asp-controller="MovieShowTime">All Movie Details with time</a>
<hr />
<h1>InsertMovieShowTimes</h1>

<form method="post">
    <div class="form-group">
        <label>Movie</label>
        <select asp-for="MovieId" asp-items="@(new SelectList(ViewBag.movieData,"Value","Text"))" class="form-control"></select>
    </div>

    <div class="form-group">
        <label>Theatre</label>
        <select asp-for="TheatreId" asp-items="@(new SelectList(ViewBag.theatreData,"Value","Text"))" class="form-control"></select>
    </div>

    <div class="form-group">
        <label>Show Time</label>
        <input type="time" class="form-control" asp-for="ShowTime" />
    </div>

    <div class="form-group">
        <label>Date</label>
        <input type="date" class="form-control" asp-for="Date" />
    </div>

    <input type="submit" value="Save" class="btn btn-primary" />
    <input type="button" value="Reset" class="btn btn-secondary" />
</form>
@if (ViewBag.status == "Success")
{
    <div class="alert alert-success">@ViewBag.message</div>
}
else if (ViewBag.status == "Error")
{
    <div class="alert alert-danger">@ViewBag.message</div>
}

Views/MovieShowtime/ShowMovieTime.cshtml
@model IEnumerable<MovieApp.Entity.MovieShowtimeModel>
@{
    ViewData["Title"] = "ShowMovieTime";
}

<h1>ShowMovieTime</h1>

<hr />

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ShowId</th>
            <th>MovieId</th>
            <th>TheatreId</th>
            <th>ShowTime</th>
            <th>Date</th>
            <th>Edit</th>
            <th>delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ShowId</td>
                <td>@item.MovieId</td>
                <td>@item.TheatreId</td>
                <td>@item.ShowTime</td>
                <td>@item.Date</td>
                <td><a asp-action="UpdateMovieshowTimes" asp-controller="MovieShowtime" asp-route-ShowId=@item.ShowId>Edit</a></td>
                <td><a asp-action="DeleteMovieshowTimes" asp-controller="MovieShowtime" asp-route-ShowId=@item.ShowId>Delete</a></td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="InsertMovieShowTimes" asp-controller="MovieShowTime" class="btn btn-primary">Add-New-Show-Time</a>
</div>

Views/MovieShowtime/UpdateMovieshowTimes.cshtml
@model MovieApp.Entity.MovieShowtimeModel
@{
    ViewData["Title"] = "UpdateMovieshowTimes";
}
<a asp-action="ShowMovieTime" asp-controller="MovieShowTime">View MovieShowTime</a>
<hr />
<h1>UpdateMovieshowTimes</h1>

<div class="container">
    <form method="post">
        <div class="form-group">
            <label>ShowId</label>
            <input asp-for="ShowId" class="form-control" />
        </div>
        <div class="form-group">
            <label>MovieId</label>
            <input asp-for="MovieId" class="form-control" />
        </div>
        <div class="form-group">
            <label>TheatreId</label>
            <input asp-for="TheatreId" class="form-control" />
        </div>

        <div class="form-group">
            <label>ShowTime</label>
            <input type="time" asp-for="ShowTime" class="form-control" />
        </div>

        <div class="form-group">
            <label>Date</label>
            <input type="date" asp-for="Date" class="form-control" />
        </div>

        <hr />
        <div class="form-group col-sm-3">
            <input type="submit" value="Update" class="btn btn-lg btn-block btn-primary" />
        </div>
        <div>
            <input type="button" value="Reset" class="btn-secondary" />
        </div>

        <hr />
        @if (ViewBag.status == "Success")
        {
            <div class="alert alert-success">
                @ViewBag.message
            </div>
        }
        else if (ViewBag.status == "Error")
        {
            <div class="alert alert-danger">
                @ViewBag.message
            </div>
        }
    </form>
</div>