Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using MovieApp.Entity;
using System.Text;
using Newtonsoft.Json;

namespace MovieApp.UI.Controllers
{
    public class MovieController : Controller
    {
        IConfiguration _configuration;

        public MovieController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> ShowMovieDetails()
        {
            using(HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiUrl"] + "User/GetMovies";
                using(var response= await client.GetAsync(endpoint))
                {
                    if(response.StatusCode== System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var movieModel = JsonConvert.DeserializeObject<List<MovieModel>>(result);
                        return View(movieModel);
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Cannot fetch any data";
                    }
                }
            }
            return View();
        }

        public async Task<IActionResult> Register(MovieModel movieModel)
        {
            using(HttpClient client= new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(movieModel), Encoding.UTF8, "application/json");
                string endpoint = _configuration["WebApiUrl"] + "Movie/RegisterMovie";
                using(var reponse= await client.PostAsync(endpoint,content))
                {
                    if(reponse.StatusCode== System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = "Registration Successful";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Registration Unsuccessful";
                    }
                }
            }
            return View();
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using MovieApp.Entity;
using Newtonsoft.Json;
using System.Text;

namespace MovieApp.UI.Controllers
{
    public class UserController : Controller
    {
        IConfiguration _iConfiguration;

        public UserController(IConfiguration configuration)
        {
            _iConfiguration = configuration;
        }
        public async Task<IActionResult> ShowUserDetails()
        {
            using(HttpClient client= new HttpClient())
            {
                string endPoint = _iConfiguration["WebApiUrl"] + "User/SelectUsers";
                using(var response= await client.GetAsync(endPoint))
                {
                    if(response.StatusCode== System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var userModel = JsonConvert.DeserializeObject<List<UserModel>>(result);
                        return View(userModel);
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Cant fetch any data";
                    }
                }
            }
            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserModel userModel)
        {
            using(HttpClient client= new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(userModel), Encoding.UTF8, "application/json");
                string endpoint = _iConfiguration["WebApiUrl"] + "User/Register";
                using(var response= await client.PostAsync(endpoint,content))
                {
                    if(response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = "Registration Successful";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Registration Unsuccessful";
                    }
                }
            }
            return View();
        }

        public async Task<IActionResult> UpdateUser(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _iConfiguration["WebApiUrl"] + "User/GetUserById?id="+id;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var userModel = JsonConvert.DeserializeObject<UserModel>(result);
                        return View(userModel);
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Cant fetch any data";
                    }
                }
            }
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> UpdateUser(UserModel userModel)
        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(userModel), Encoding.UTF8, "application/json");
                string endpoint = _iConfiguration["WebApiUrl"] + "User/Update";
                using (var response = await client.PutAsync(endpoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = "Updation Successful";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Registration Unsuccessful";
                    }
                }
            }
            return View();
        }


        public async Task<IActionResult> DeleteUser(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _iConfiguration["WebApiUrl"] + "User/GetUserById?id=" + id;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        var userModel = JsonConvert.DeserializeObject<UserModel>(result);
                        return View(userModel);
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Cant fetch any data";
                    }
                }
            }
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> DeleteUser(UserModel userModel)
        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(userModel), Encoding.UTF8, "application/json");
                string endpoint = _iConfiguration["WebApiUrl"] + "User/Delete?id="+userModel.UserId;
                using (var response = await client.PutAsync(endpoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = "Deletion Successful";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Registration Unsuccessful";
                    }
                }
            }
            return View();
        }
    }
}

Views/Movie/DeleteMovie.cshtml
@model MovieApp.Entity.MovieModel
@{
    ViewData["Title"] = "DeleteMovie";
}

<h1>DeleteMovie</h1>

<form method="post">
    <div class="form-group">
        <label for="fName">ID:</label>
        <input type="text" class="form-control" id="fname" asp-for="Id" disabled="disabled">
    </div>
    <div class="form-group">
        <label for="fName">Name:</label>
        <input type="text" class="form-control" id="fname" asp-for="Name" disabled="disabled">
    </div>
    <div class="form-group">
        <label for="contact">Rating:</label>
        <input type="text" class="form-control" id="contact" asp-for="Rating" disabled="disabled">
    </div>
    <div class="form-group">
        <label for="email">Genre:</label>
        <input type="text" class="form-control" id="email" asp-for="Genre" disabled="disabled">
    </div>

    <button type="submit" class="btn btn-primary">Delete</button>
    <button type="reset" class="btn btn-secondary">Reset</button>
</form>

@if (ViewBag.status == "Success")
{
    <div class="alert alert-success">@ViewBag.message</div>
}
else
{
    <div class="alert alert-danger">@ViewBag.message</div>
}

Views/Movie/Register.cshtml
@model MovieApp.Entity.MovieModel
@{
    ViewData["Title"] = "Register";
}
<a asp-action="ShowMovieDetails" asp-controller="Movie">Movie Details</a>
<hr />
<h1>Register</h1>

<form method="post">
    <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" class="form-control" id="name" asp-for="Name">
    </div>
    <div class="form-group">
        <label for="lName">Rating:</label>
        <input type="text" class="form-control" id="rating" asp-for="Rating">
    </div>
    <div class="form-group">
        <label for="contact">Genre:</label>
        <input type="text" class="form-control" id="Genre" asp-for="Genre">
    </div>

    <button type="submit" class="btn btn-primary">Register</button>
    <button type="reset" class="btn btn-secondary">Reset</button>
</form>

@if (ViewBag.status == "Success")
{
    <div class="alert alert-success">@ViewBag.message</div>
}
else
{
    <div class="alert alert-danger">@ViewBag.message</div>
}

Views/Movie/ShowMovieDetails.cshtml
@model IEnumerable<MovieApp.Entity.MovieModel>
@{
    ViewData["Title"] = "ShowMovieDetails";
}

<h1>ShowMovieDetails</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Rating</th>
            <th>Genre</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var items in Model)
        {
            <tr>
                <td>@items.Id</td>
                <td>@items.Name</td>
                <td>@items.Rating</td>
                <td>@items.Genre</td>
                <td><a asp-action="UpdateUser" asp-controller="User" asp-route-UserId="@items.Id">Edit</a></td>
                <td><a asp-action="DeleteUser" asp-controller="User" asp-route-UserId="@items.Id">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

Views/Movie/UpdateMovie.cshtml
@model MovieApp.Entity.MovieModel
@{
    ViewData["Title"] = "UpdateMovie";
}

<h1>UpdateMovie</h1>

<form method="post">
    <div class="form-group">
        <label for="fName">Name:</label>
        <input type="text" class="form-control" id="name" asp-for="Name">
    </div>
    <div class="form-group">
        <label for="lName">Rating:</label>
        <input type="text" class="form-control" id="lname" asp-for="Rating">
    </div>
    <div class="form-group">
        <label for="email">Genre:</label>
        <input type="text" class="form-control" id="email" asp-for="Genre">
    </div>
    
    <button type="submit" class="btn btn-primary">Update</button>
    <button type="reset" class="btn btn-secondary">Reset</button>
</form>

@if (ViewBag.status == "Success")
{
    <div class="alert alert-success">@ViewBag.message</div>
}
else
{
    <div class="alert alert-danger">@ViewBag.message</div>
}